# Tensor

## Import

In [2]:
import tensorflow as tf
import numpy as np

## Basic

 ### scalar


In [5]:
r_0_ts = tf.constant(4)
print(r_0_ts)

tf.Tensor(4, shape=(), dtype=int32)


### vector

In [8]:
r_1_ts = tf.constant([1., 2., 3.])
print(r_1_ts)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


### matrix

In [9]:
r_2_ts = tf.constant([[1., 2., 3.], [4., 5., 6.]])
print(r_2_ts)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


### more axes

In [12]:
r_m_ts = tf.constant([[[1, 2, 3],[1, 2, 3]],
                       [[2, 3, 4], [7, 8, 9]], 
                       [[3, 4, 5], [5, 6, 7]]])
print(r_m_ts)

tf.Tensor(
[[[1 2 3]
  [1 2 3]]

 [[2 3 4]
  [7 8 9]]

 [[3 4 5]
  [5 6 7]]], shape=(3, 2, 3), dtype=int32)


### convert to numpy

In [14]:
np.array(r_m_ts)
r_m_ts.numpy()

array([[[1, 2, 3],
        [1, 2, 3]],

       [[2, 3, 4],
        [7, 8, 9]],

       [[3, 4, 5],
        [5, 6, 7]]])

### basic math 

In [16]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2], dtype=tf.int32)`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [19]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [20]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.math.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105854e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


### convert to tensor

In [23]:
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [26]:
print(tf.reduce_max([[1,2,3], [4, 5, 6]]))

tf.Tensor(6, shape=(), dtype=int32)


In [28]:
tf.reduce_max(np.array([1,2,3]))

<tf.Tensor: shape=(), dtype=int32, numpy=3>

### About shapes
- Tensors have shapes. Some vocabulary:

    - Shape: The length (number of elements) of each of the axes of a tensor.
    - Rank: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
    - Axis or Dimension: A particular dimension of a tensor.
    - Size: The total number of items in the tensor, the product of the shape vector's elements.

In [30]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

In [35]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim) # not return tensor
print("Shape of tensor:", rank_4_tensor.shape) # not return tensor
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


In [37]:
tf.rank(rank_4_tensor) # replace ndim it return tensor, but a scalar
tf.shape(rank_4_tensor) # replace shape, it's a vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 4, 5])>

### Indexing

In [39]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())    
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

[ 0  1  1  2  3  5  8 13 21 34]
First: 0
Second: 1
Last: 34


In [43]:
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


In [45]:
rank_2_tensor = tf.constant([[1., 2., 3.], [4., 5., 6.]])
print(rank_2_tensor.numpy())

[[1. 2. 3.]
 [4. 5. 6.]]


In [46]:
# Pull out a single value from a 2-rank tensor
print(rank_2_tensor[1, 1].numpy())

5.0


In [59]:
# Get row and column tensors
print("Second row:", rank_2_tensor[1:, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1::-1, -1::-1].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

Second row: [[4. 5. 6.]]
Second column: [2. 5.]
Last row: [[6. 5. 4.]
 [3. 2. 1.]]
First item in last column: 3.0
Skip the first row:
[[4. 5. 6.]] 

