# Tensor

In [5]:
import tensorflow as tf

x = tf.constant([[1., 2., 3.],
                [4., 5., 6.]])

print(type(x))

print(x)

print(x.shape)

print(x.dtype)

print(x.numpy())


<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>
[[1. 2. 3.]
 [4. 5. 6.]]
