In [2]:
import numpy as np

In [12]:
one_dimen_array = np.array([1., 2., 3., 4., 5.])
two_dimen_array = np.array([[1., 2., 3., 4., 5.],
                           [6., 7., 8., 9., 10.]])
sequency_array = np.arange(start=1, stop=10, step=1.5, dtype=np.float32)

print(one_dimen_array)
print(two_dimen_array)
print(sequency_array)


[1. 2. 3. 4. 5.]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
[1.  2.5 4.  5.5 7.  8.5]


### np.random

#### randint

In [5]:
random_array = np.random.randint(low=0, high=10, size=(6,))
print(random_array)



[1 4 2 4 8 0]


#### random

In [6]:
random_float_array = np.random.random(size=(6,))
print(random_float_array)




[0.20859968 0.89731533 0.4787475  0.54855553 0.44319939 0.25569421]


### Mathematical operations

In [7]:
add2_array = random_array + 2
print(add2_array)




[ 3  6  4  6 10  2]


In [8]:
mul2_array = random_array * 2
print(mul2_array)



[ 2  8  4  8 16  0]


## Additional

#### array create

In [15]:
zero_array = np.zeros(shape=(6,))
one_array = np.ones(shape=(6,))
full_array = np.full(shape=(6,3), fill_value=10)
eye_array = np.eye(N=6, M=3, k=0)

print(zero_array)
print(one_array)
print(full_array)
print(eye_array)



[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### array operate

In [23]:
a = np.random.random(size=(6, 2))
print(a)    
print(np.reshape(a, newshape=(1, 12)))


[[0.73939341 0.77044428]
 [0.92590232 0.81131879]
 [0.81043486 0.63591717]
 [0.14190915 0.27529566]
 [0.9423473  0.38607516]
 [0.71870483 0.94429567]]
[[0.73939341 0.77044428 0.92590232 0.81131879 0.81043486 0.63591717
  0.14190915 0.27529566 0.9423473  0.38607516 0.71870483 0.94429567]]


In [22]:
np.ravel(a)

array([0.58817237, 0.52731479, 0.51802361, 0.49538732, 0.64495599,
       0.74612155, 0.54112072, 0.80458088, 0.88517446, 0.21811101,
       0.07416229, 0.20264008])

In [24]:
np.transpose(a)

array([[0.73939341, 0.92590232, 0.81043486, 0.14190915, 0.9423473 ,
        0.71870483],
       [0.77044428, 0.81131879, 0.63591717, 0.27529566, 0.38607516,
        0.94429567]])

#### mathematical operate

In [30]:
b = np.random.random(size=(6, 2))
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))
c = np.random.random(size=(2, 3))
print(np.dot(a, c))



[[1.72841907 1.13411554]
 [1.05189361 1.67206679]
 [1.4226603  1.29103983]
 [0.59040815 0.7322671 ]
 [1.80845001 1.20706231]
 [1.53464611 1.4645267 ]]
[[-0.24963224  0.40677302]
 [ 0.79991102 -0.04942922]
 [ 0.19820943 -0.01920549]
 [-0.30658985 -0.18167579]
 [ 0.0762446  -0.43491199]
 [-0.09723645  0.42406464]]
[[0.73127905 0.28018844]
 [0.11665564 0.69834103]
 [0.49616884 0.41660375]
 [0.06364611 0.12580225]
 [0.81616955 0.31696275]
 [0.58642094 0.49125191]]
[[0.74759781 2.11851849]
 [7.34893857 0.94257411]
 [1.32375236 0.97068414]
 [0.31640906 0.60243514]
 [1.08803183 0.47025725]
 [0.8808291  1.81514677]]
[[0.38525974 0.22046709 0.75555226]
 [0.47234478 0.25637777 0.84232533]
 [0.40855713 0.21487698 0.68707241]
 [0.08232374 0.05867185 0.23120779]
 [0.4518135  0.20449101 0.55988464]
 [0.38733406 0.23938383 0.86659478]]


#### statistics function

In [31]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.sum(a))

0.6751698829068719
0.7549188453932838
0.2562538552439034
0.0656660383273634
8.102038594882462


#### linear algebra

In [33]:
matrix = np.array([[1, 2], [3, 4]])
print(np.linalg.det(matrix))
print(np.linalg.inv(matrix))


-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
