In [1]:
import numpy as np

In [2]:
one_dimen_array = np.array([1., 2., 3., 4., 5.])
two_dimen_array = np.array([[1., 2., 3., 4., 5.],
                           [6., 7., 8., 9., 10.]])
sequency_array = np.arange(start=1, stop=10, step=1.5, dtype=np.float32)

print(one_dimen_array)
print(two_dimen_array)
print(sequency_array)


[1. 2. 3. 4. 5.]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
[1.  2.5 4.  5.5 7.  8.5]


### np.random

#### randint

In [3]:
random_array = np.random.randint(low=0, high=10, size=(6,))
print(random_array)



[8 8 9 0 2 3]


#### random

In [4]:
random_float_array = np.random.random(size=(6,))
print(random_float_array)




[0.34367498 0.68640053 0.80549338 0.83807405 0.41058042 0.67122161]


### Mathematical operations

In [5]:
add2_array = random_array + 2
print(add2_array)




[10 10 11  2  4  5]


In [6]:
mul2_array = random_array * 2
print(mul2_array)



[16 16 18  0  4  6]


## Additional

#### array create

In [7]:
zero_array = np.zeros(shape=(6,))
one_array = np.ones(shape=(6,))
full_array = np.full(shape=(6,3), fill_value=10)
eye_array = np.eye(N=6, M=3, k=0)

print(zero_array)
print(one_array)
print(full_array)
print(eye_array)



[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### array operate

In [8]:
a = np.random.random(size=(6, 2))
print(a)    
print(np.reshape(a, newshape=(1, 12)))


[[0.42910872 0.56632823]
 [0.59069134 0.38304285]
 [0.41015547 0.61484729]
 [0.70016229 0.44782909]
 [0.36704986 0.6296514 ]
 [0.54789975 0.5294917 ]]
[[0.42910872 0.56632823 0.59069134 0.38304285 0.41015547 0.61484729
  0.70016229 0.44782909 0.36704986 0.6296514  0.54789975 0.5294917 ]]


In [9]:
np.ravel(a)

array([0.42910872, 0.56632823, 0.59069134, 0.38304285, 0.41015547,
       0.61484729, 0.70016229, 0.44782909, 0.36704986, 0.6296514 ,
       0.54789975, 0.5294917 ])

In [10]:
np.transpose(a)

array([[0.42910872, 0.59069134, 0.41015547, 0.70016229, 0.36704986,
        0.54789975],
       [0.56632823, 0.38304285, 0.61484729, 0.44782909, 0.6296514 ,
        0.5294917 ]])

#### mathematical operate

In [11]:
b = np.random.random(size=(6, 2))
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))
c = np.random.random(size=(2, 3))
print(np.dot(a, c))



[[0.53523377 1.13536575]
 [1.38238055 1.24659237]
 [0.51637694 0.75899568]
 [1.27509829 0.7527126 ]
 [1.03796018 1.26203938]
 [1.07568212 0.76417025]]
[[ 0.32298367 -0.0027093 ]
 [-0.20099786 -0.48050667]
 [ 0.30393401  0.4706989 ]
 [ 0.12522628  0.14294559]
 [-0.30386045 -0.00273659]
 [ 0.02011737  0.29481314]]
[[0.04553918 0.32226201]
 [0.46764396 0.33077647]
 [0.04356731 0.08862925]
 [0.40254851 0.13653571]
 [0.24625754 0.39818398]
 [0.28917183 0.12426035]]
[[4.04342542 0.99523881]
 [0.74611519 0.4435679 ]
 [3.86132389 4.2653775 ]
 [1.21780908 1.46885313]
 [0.54709229 0.99567261]
 [1.0381168  2.25624237]]
[[0.66806548 0.3378412  0.16577452]
 [0.65502692 0.25572223 0.22261673]
 [0.68762481 0.3617376  0.15948735]
 [0.7722826  0.29984042 0.2637863 ]
 [0.66835484 0.36564771 0.14384368]
 [0.72381288 0.32915661 0.2089413 ]]


#### statistics function

In [12]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.sum(a))

0.5180214990505806
0.5386957204057381
0.10373430073645686
0.010760805149281674
6.2162579886069675


#### linear algebra

In [14]:
matrix = np.array([[1, 2], [3, 4]])
print(np.linalg.det(matrix))
print(np.linalg.inv(matrix))


-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
